name: Docker Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pedidos-service
        uses: docker/build-push-action@v5
        with:
          context: ./pedidos-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pedidos-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push pagamento-service
        uses: docker/build-push-action@v5
        with:
          context: ./pagamento-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pagamento-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push envio-service
        uses: docker/build-push-action@v5
        with:
          context: ./envio-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/envio-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 