name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'  # Padrão para tags SemVer
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  # Extrai a versão da tag (remove o 'v' inicial)
  PROJECT_VERSION: ${{ github.ref_name != 'main' && github.ref_name || 'latest' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para obter todas as tags

      - name: Get version from tag
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove o 'v' inicial se existir
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build and push pedidos-service
        uses: docker/build-push-action@v5
        with:
          context: ./pedidos-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pedidos-service:${{ steps.get_version.outputs.version || 'latest' }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pedidos-service:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build and push pagamento-service
        uses: docker/build-push-action@v5
        with:
          context: ./pagamento-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pagamento-service:${{ steps.get_version.outputs.version || 'latest' }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pagamento-service:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build and push envio-service
        uses: docker/build-push-action@v5
        with:
          context: ./envio-service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/envio-service:${{ steps.get_version.outputs.version || 'latest' }}
            ${{ env.IMAGE_NAME }}/envio-service:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }} 